const billionaires = [
  {
    id: 1,
    name: 'Elon Musk',
    title: 'CEO at SpaceX and Tesla, Inc.',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_elon.png',
    price: 3250.0,
    description: 'Elon Musk is a business magnate and investor. He is the founder, CEO, and Chief Engineer at SpaceX; angel investor, CEO, and Product Architect of Tesla, Inc.; founder of The Boring Company; and co-founder of Neuralink and OpenAI. With an estimated net worth of around US$265 billion as of May 2022, Musk is the wealthiest person in the world according to both the Bloomberg Billionaires Index and the Forbes real-time billionaires list.',
    created_at: '2022-06-08T08:54:03.640Z',
    updated_at: '2022-06-08T08:54:03.640Z',
  },
  {
    id: 2,
    name: 'Jeff Bezos',
    title: 'Founder of Amazon',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_jeff.png',
    price: 2650.0,
    description: "Jeff Bezos is an American entrepreneur, media proprietor, investor, computer engineer, and commercial astronaut. He is the founder, executive chairman and former president and CEO of Amazon. With a net worth of around US$140 billion as of May 2022, Bezos is the second-wealthiest person in the world and was the wealthiest from 2017 to 2021 according to both Bloomberg's Billionaires Index and Forbes.",
    created_at: '2022-06-08T08:54:03.648Z',
    updated_at: '2022-06-08T08:54:03.648Z',
  },
  {
    id: 3,
    name: 'Ariel Camus',
    title: 'Founder & CEO at Microverse',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_ariel.png',
    price: 4350.0,
    description: 'The Argentine-born has founded multiple projects, including the one where is currently CEO: Microverse, a school that enables job-opportunities for talent around the world. Ariel has lived and worked in 7 different countries including Spain, Argentina, USA, and Vietnam and has been coding since he was 12. He previously founded Tourist Eye, a travel app with 1MM+ users acquired by Lonely Planet.',
    created_at: '2022-06-08T08:54:03.655Z',
    updated_at: '2022-06-08T08:54:03.655Z',
  },
  {
    id: 4,
    name: 'Julia Koch',
    title: 'President of David H. Koch Foundation',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_julia.png',
    price: 2900.0,
    description: "Julia Koch is an American socialite, billionaire, philanthropist, and one of the richest women in the world. She inherited her fortune from her husband, David Koch, who died in 2019. As of January 2020, Forbes estimates her and her family's net worth at $43 billion, while Bloomberg estimates it at $61.6 billion.",
    created_at: '2022-06-08T08:54:03.661Z',
    updated_at: '2022-06-08T08:54:03.661Z',
  },
  {
    id: 5,
    name: 'Alice Walton',
    title: 'Heiress, Walton family fortune',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_alice.png',
    price: 2800.0,
    description: 'Alice Walton is an American heiress to the fortune of Walmart. In September 2016, she owned over US$11 billion in Walmart shares.[3] As of March 2022, Walton has a net worth of $60.5 billion, making her the 20th-richest person, and the second richest woman in the world according to Bloomberg Billionaires Index.',
    created_at: '2022-06-08T08:54:03.668Z',
    updated_at: '2022-06-08T08:54:03.668Z',
  },
  {
    id: 6,
    name: 'Jack Ma',
    title: 'Co-founder of Yunfeng Capital',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_jack.png',
    price: 2290.0,
    description: 'Jack Ma is a Chinese business magnate, investor and philanthropist. He is the co-founder and former executive chairman of Alibaba Group, a multinational technology conglomerate. In addition, he co-founded Yunfeng Capital, a Chinese private equity firm. Ma is a strong proponent of an open and market-driven economy.',
    created_at: '2022-06-08T08:54:03.675Z',
    updated_at: '2022-06-08T08:54:03.675Z',
  },
  {
    id: 7,
    name: 'Francoise Meyers',
    title: "Chairwoman at L'Oréal",
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_francoise.png',
    price: 3900.0,
    description: "Francoise Meyers is a French businesswoman, philanthropist, writer, pianist and billionaire heiress, the richest woman in the world, with an estimated net worth of US$75.3 billion as of March 2022, according to Forbes. She is the only child, heiress of Liliane Bettencourt and granddaughter of L'Oréal founder Eugène Schueller. Her mother died in September 2017, after which her fortune tripled with her investments through her family holding company, Tethys Invest, and the high valuation of L'Oréal shares on the stock exchange.",
    created_at: '2022-06-08T08:54:03.681Z',
    updated_at: '2022-06-08T08:54:03.681Z',
  },
  {
    id: 8,
    name: 'Changpeng Zhao',
    title: 'Founder & CEO at Binance',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_chang.png',
    price: 3500.0,
    description: "Changpeng Zhao commonly known as 'CZ', is a Chinese-Canadian business executive. Zhao is the founder and CEO of Binance, the world's largest cryptocurrency exchange by trading volume as of April 2018. CZ was born in Jiangsu, China and moved to Canada at a young age with his family.",
    created_at: '2022-06-08T08:54:03.687Z',
    updated_at: '2022-06-08T08:54:03.687Z',
  },
  {
    id: 9,
    name: 'Mark Zuckerberg',
    title: 'Co-founder & CEO of Meta Platforms',
    image: 'https://raw.githubusercontent.com/orozCoding/billionares-pictures/main/round_pictures/pc_mark.png',
    price: 2980.0,
    description: 'Mark Zuckerberg is an American media magnate, internet entrepreneur, and philanthropist. He is known for co-founding the social media website Facebook and its parent company Meta Platforms (formerly Facebook, Inc.), of which he is the chairman, chief executive officer, and controlling shareholder.',
    created_at: '2022-06-08T08:54:03.694Z',
    updated_at: '2022-06-08T08:54:03.694Z',
  },
  {
    id: 10,
    name: 'Bill Gates',
    title: 'Co-founder of Microsoft',
    image: 'https://github.com/orozCoding/billionares-pictures/blob/main/round_pictures/pc_bill.png?raw=true',
    price: 3120.0,
    description: 'Billgates is an American business magnate, software developer, investor, author, and philanthropist. He is a co-founder of Microsoft, along with his late childhood friend Paul Allen. During his career at Microsoft, Gates held the positions of chairman, chief executive officer (CEO), president and chief software architect, while also being the largest individual shareholder until May 2014. He was a major entrepreneur of the microcomputer revolution of the 1970s and 1980s.',
    created_at: '2022-06-08T08:54:03.700Z',
    updated_at: '2022-06-08T08:54:03.700Z',
  },
];

export default billionaires;

export const readableTime = (time) => time.slice(0, 10);
